apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: cast
      {{- include "fastapiapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cast
        {{- include "fastapiapp.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cast-service
          image: "{{ .Values.cast_service.image.repository }}:{{ .Values.cast_service.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://cast_db_username:cast_db_password@cast-db-svc/cast_db_dev"